apiVersion: batch/v1
kind: Job
metadata:
  name: start-web-build
  namespace: checker
spec:
  template:
    spec:
      containers:
      - name: build
        image: 'openshift/origin-cli:latest'
        command: ['oc', 'start-build', 'web-buildconfig', '-n', 'checker']
      restartPolicy: Never
  backoffLimit: 4
