apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  annotations:
     image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"web:v1","namespace":"checker"},"fieldPath":"spec.template.spec.containers[?(@.name==\"container\")].image","pause":"false"}]
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-mysql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: web-mysql
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/checker/web:v1
        imagePullPolicy: IfNotPresent
        name: container
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
