kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: web-buildconfig
spec:
  output:
    to:
      kind: DockerImage
      name: 'image-registry.openshift-image-registry.svc:5000/checker/web:v1'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'image-registry.openshift-image-registry.svc:5000/openshift/python:3.9-ubi8'
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/cellist01/ex280-networkpolicy-app.git'
    contextDir: /web-src
  runPolicy: Serial
